#!/bin/sh
if [ $(which convert 2>&1|grep ^/|wc -l) -lt 1 ]; then 
   echo "${SPECIALPREFIX}failed:convert" 1>&2
   echo "maybe install imagemagick" 1>&2
   rm -f .tmp/proof-convert
   exit 1
fi
touch .tmp/proof-convert
