#!/bin/sh
if [ $(which pdftoppm 2>&1|grep ^/|wc -l) -lt 1 ]; then 
   echo "${SPECIALPREFIX}failed:pdftoppm" 1>&2
   echo "maybe install poppler-utils" 1>&2
   rm -f .tmp/proof-pdftoppm
   exit 1
fi
touch .tmp/proof-pdftoppm