#!/bin/sh
set -e
for i in "$@"; do
    if [ "$1" = "full" ]; then
        echo "all" > pions/wanted.txt
    else
        cp pions/${i}.txt pions/wanted.txt
    fi
    bin/filedownloader pions
done
rm -f pions/wanted.txt
