#!/bin/sh
set -e
DEST=pions/counters.txt
RELEASE=$(grep ^release= doc/release.txt|cut -f2- -d=|xargs printf %s)
echo "This is the list of counters for release $RELEASE" > $DEST
echo >> $DEST
cat $(cat plan/in/pionscounterslist.in)|uniq -c|sort -t'#' -k2 | cut -f1,3 -d'#'|sed -e 's/ #/\t/g'>> $DEST
